server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: Bulunmaz3457
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
